- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: promfetcher
    scheme: https
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
          - /var/vcap/store/bosh_exporter/bosh_target_groups.json
    relabel_configs:
      - action: keep
        regex: promfetcher
        source_labels:
          - __meta_bosh_job_process_name
      - regex: (.*)
        replacement: ${1}:443
        source_labels:
          - __address__
        target_label: __address__

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=promfetcher_alerts?
  value:
    name: promfetcher_alerts
    release: promfetcher
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value:
    /var/vcap/jobs/promfetcher_alerts/*.alerts.yml

- type: replace
  path: /releases/-
  value:
    name: promfetcher
    version: latest